export const summariePolicyList = [
    {
      name: 'jp morgan',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'xvideos',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'pornhub',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'pinterest',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'espn',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'ebay',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'discord',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'twich',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'indeed',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'zoom',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
    {
      name: 'example',
      policyWebpage: '',
      privacyTerms: [],
      vigencyOfPrivacy: '',
      conditionsTerms: [],
      vigencyofUseTerms: '',
    },
]